preset: symfony

linting: true

enabled:
  - short_array_syntax
  - strict

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
  not-name:
    - "*Stub.php"
  contains:
    - "Stef"
  not-contains:
    - "config"
  path:
    - "src/Stef"
  not-path:
    - "libraries"
  depth:
    - "< 3"